[package]
name = "wie-core-arm"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
bytemuck = { workspace = true }
spin = { workspace = true }
tracing = { workspace = true }

arm32_cpu = { version = "^0.1.2" }
crossbeam = { version = "^0.8" }
gdbstub = { version = "^0.7" }
gdbstub_arch = { version = "^0.3" }

wie-backend = { workspace = true }
wie-arm-jit-types = { workspace = true }
wie-util = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wie-core-arm-wasm = { workspace = true }

[dev-dependencies]
futures = { workspace = true, features = ["executor"] }
futures-test = { workspace = true }
test-utils = { workspace = true }
wie-core-arm-wasm = { workspace = true }
