[package]
name = "wie-ktf-dump"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true, features = ["executor"] }

wie-ktf = { workspace = true }
