[package]
name = "wie-web"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ["-O", "-g", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
async-trait = { version = "^0.1" }
anyhow = { version = "^1.0" }
console_error_panic_hook = { version = "^0.1" }
futures = { version = "^0.3", default-features = false, features = ["alloc"] }
hashbrown = { version = "^0.17" }
js-sys = { version = "^0.3" }
time = { version = "^0.3", features = ["wasm-bindgen"] }
tracing = { version = "^0.1", features = ["release_max_level_info"] }
tracing-subscriber = { version = "^0.3", features = ["time"] }
tracing-web = { version = "^0.1" }
wasm-bindgen = { version = "^0.2" }
wasm-bindgen-futures = { version = "^0.4" }
web-sys = { version = "^0.3", features = ["HtmlCanvasElement", "CanvasRenderingContext2d", "ImageData", "Window", "Navigator"] }

wie-backend = { workspace = true }
wie-ktf = { workspace = true }
wie-lgt = { workspace = true }
wie-skt = { workspace = true }
wie-j2me = { workspace = true }
wie-util = { workspace = true }
