name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache cargo
        uses: actions/cache/restore@v6
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Cache cargo build
        uses: actions/cache/restore@v6
        with:
          path: target
          key: ${{ runner.os }}-stable-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-stable-build-target-

      - name: Install required packages
        run: sudo apt update;sudo apt install -y libwebkit2gtk-4.1-dev libasound2-dev

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Save cache cargo
        uses: actions/cache/save@v6
        if: github.ref == 'refs/heads/main'
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Save cache cargo build
        uses: actions/cache/save@v6
        if: github.ref == 'refs/heads/main'
        with:
          path: target
          key: ${{ runner.os }}-stable-build-target-${{ hashFiles('**/Cargo.lock') }}
